name: Run Tests

on:
  push:
    branches: [ "main", "dev" ]
  workflow_dispatch:

jobs:
  setup_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Verify Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install kaggle CLI
        run: pip install kaggle

      - name: Set up kaggle directory
        run: mkdir -p ~/.kaggle

      - name: Set up kaggle credentials
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          echo "{\"username\":\"$KAGGLE_USERNAME\",\"key\":\"$KAGGLE_API_TOKEN\"}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          cat ~/.kaggle/kaggle.json

      - name: Download dataset
        run: kaggle datasets download -d alexandredj/rock-paper-scissors-dataset
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}

      - name: Unzip dataset
        run: unzip national-flowers.zip
        
      - name: Test with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: pytest